config/routes.rb
Rails.application.routes.draw do

    root "gossips#index"
    resources :gossips
    
    get '/new', to: 'gossips#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	
	def index
	 	@gossips = Gossip.all
	end

	def new
		@gossip= Gossip.new
	end

	def create
		@gossip = Gossip.new(gossip_params)
        @gossip.save
        redirect_to @gossip
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		if @gossip.update(gossip_params)
			redirect_to @gossip
		else 
			render 'edit'
			
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	private

    	def gossip_params
      params.require(:gossip).permit(:anonymous_author, :content)

  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
  <p> <%= label_tag 'anonymous_author', "Si vous avez oublié votre prénom, inventez en un !" %> </p>
  <p> <%= text_field_tag 'anonymous_author' %> </p>

  <p> <%= label_tag 'content', "Modifiez ci dessous:" %> </p>
  <p> <%= text_area_tag 'content' %> </p>

app/views/gossips/edit.html.erb
<h1> Editer ce gossip </h1>
 
<%= render 'form', gossip: @gossip %>
 
<%= submit_tag "Modifier le gossip"%>

<p> <%= link_to('Retour aux gossips', gossips_path) %> </p> 

app/views/gossips/index.html.erb
<h1> Gossips Actu </h1>


<table>
  <tr>
    <th>Source</th>
    <th>Gossip</th>
  </tr>

  <% @gossips.each do |gossip| %> 

    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to "Voir", gossip_path(gossip) %></td>
      <td><%= link_to "Editer", edit_gossip_path(gossip) %></td>
      <td> <%= link_to "Supprimer", gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Vous êtes sur le point de supprimer un gossip croustillant, êtes vous sûrs?' } %> </td>

    </tr>
  <% end %>
</table>

<p> <%= link_to('Une info toute chaude ?', new_gossip_path ) %> </p>

app/views/gossips/new.html.erb
<h1> Nouveau Gossip </h1>

<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :anonymous_author %>
</br></br>
  <%= f.text_area :content %>
</br>
</br>
  <%= f.submit "Enregistrer" %>
<% end %>

app/views/gossips/show.html.erb
<h2> <%= @gossip.anonymous_author %> </h2>
<p> <%= @gossip.content %> </p>

<p> <%= link_to('Edit', edit_gossip_path) %> </p> 
<p> <%= link_to('Retour aux Gossips', gossips_path) %> </p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>